<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Test" duration-ms="53" started-at="2019-02-10T13:46:13Z" finished-at="2019-02-10T13:46:13Z">
    <groups>
      <group name="A">
        <method signature="NewTest.f()[pri:0, instance:TestNNNNNG.NewTest@51565ec2]" name="f" class="TestNNNNNG.NewTest"/>
        <method signature="NewTest.f2()[pri:0, instance:TestNNNNNG.NewTest@51565ec2]" name="f2" class="TestNNNNNG.NewTest"/>
        <method signature="NewTest.f4()[pri:0, instance:TestNNNNNG.NewTest@51565ec2]" name="f4" class="TestNNNNNG.NewTest"/>
      </group> <!-- A -->
    </groups>
    <test name="testNGgrouping" duration-ms="53" started-at="2019-02-10T13:46:13Z" finished-at="2019-02-10T13:46:13Z">
      <class name="TestNNNNNG.NewTest">
        <test-method status="FAIL" signature="f()[pri:0, instance:TestNNNNNG.NewTest@51565ec2]" name="f" duration-ms="19" started-at="2019-02-10T13:46:13Z" finished-at="2019-02-10T13:46:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at TestNNNNNG.NewTest.f(NewTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f2()[pri:0, instance:TestNNNNNG.NewTest@51565ec2]" name="f2" duration-ms="1" started-at="2019-02-10T13:46:13Z" finished-at="2019-02-10T13:46:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f2 -->
        <test-method status="PASS" signature="f4()[pri:0, instance:TestNNNNNG.NewTest@51565ec2]" name="f4" duration-ms="1" started-at="2019-02-10T13:46:13Z" finished-at="2019-02-10T13:46:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f4 -->
      </class> <!-- TestNNNNNG.NewTest -->
    </test> <!-- testNGgrouping -->
  </suite> <!-- Test -->
</testng-results>
